#pragma once

enum class PackageType {BASE = -1, REBUILD_SCRIPTS_REQUESTED = 0, CHUNK_LOADED, CHUNK_DELETED, VOXEL_SET, GFX_ENTITY_ADDED, GFX_ENTITY_MOVED, GFX_ENTITY_ROTATED, GFX_ENTITY_REMOVED, PLAYER_ACTION, PLAYER_MOVE_DIRECTION, PLAYER_MOVE_ACTION, PLAYER_PITCH_YAW, PLAYER_CONNECTED_TO_ENTITY, PLAYER_FACING_BLOCK, PLAYER_ID};
