#pragma once

enum ShaderAttribute { 
    POSITION = 0, NORMAL,
    COLOR,
    TEXTUREINDEX,
    TEXCOORD,
    MODELMATRIX1, MODELMATRIX2, MODELMATRIX3, MODELMATRIX4,
    NORMALMATRIX1, NORMALMATRIX2, NORMALMATRIX3, NORMALMATRIX4
};
